name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Chiarelo
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
